# coding: utf-8

"""
    Aerostack API

    Aerostack Platform API - Unified access to database, authentication,  caching, queues, storage, and AI services. 

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from aerostack.models.cache_get200_response import CacheGet200Response

class TestCacheGet200Response(unittest.TestCase):
    """CacheGet200Response unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> CacheGet200Response:
        """Test CacheGet200Response
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `CacheGet200Response`
        """
        model = CacheGet200Response()
        if include_optional:
            return CacheGet200Response(
                value = None,
                exists = True
            )
        else:
            return CacheGet200Response(
        )
        """

    def testCacheGet200Response(self):
        """Test CacheGet200Response"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
