# coding: utf-8

"""
    Aerostack API

    Aerostack Platform API - Unified access to database, authentication,  caching, queues, storage, and AI services. 

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from aerostack.api.database_api import DatabaseApi


class TestDatabaseApi(unittest.TestCase):
    """DatabaseApi unit test stubs"""

    def setUp(self) -> None:
        self.api = DatabaseApi()

    def tearDown(self) -> None:
        pass

    def test_db_query(self) -> None:
        """Test case for db_query

        Execute SQL query
        """
        pass


if __name__ == '__main__':
    unittest.main()
