# coding: utf-8

"""
    Aerostack API

    Aerostack Platform API - Unified access to database, authentication,  caching, queues, storage, and AI services. 

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from aerostack.models.queue_enqueue201_response import QueueEnqueue201Response

class TestQueueEnqueue201Response(unittest.TestCase):
    """QueueEnqueue201Response unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> QueueEnqueue201Response:
        """Test QueueEnqueue201Response
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `QueueEnqueue201Response`
        """
        model = QueueEnqueue201Response()
        if include_optional:
            return QueueEnqueue201Response(
                job_id = '',
                success = True
            )
        else:
            return QueueEnqueue201Response(
        )
        """

    def testQueueEnqueue201Response(self):
        """Test QueueEnqueue201Response"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
