# coding: utf-8

"""
    Aerostack API

    Aerostack Platform API - Unified access to database, authentication,  caching, queues, storage, and AI services. 

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from aerostack.models.queue_enqueue_request import QueueEnqueueRequest

class TestQueueEnqueueRequest(unittest.TestCase):
    """QueueEnqueueRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> QueueEnqueueRequest:
        """Test QueueEnqueueRequest
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `QueueEnqueueRequest`
        """
        model = QueueEnqueueRequest()
        if include_optional:
            return QueueEnqueueRequest(
                type = 'send-email',
                data = {
                    'key' : null
                    },
                delay = 60
            )
        else:
            return QueueEnqueueRequest(
                type = 'send-email',
                data = {
                    'key' : null
                    },
        )
        """

    def testQueueEnqueueRequest(self):
        """Test QueueEnqueueRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
