# coding: utf-8

"""
    Aerostack API

    Aerostack Platform API - Unified access to database, authentication,  caching, queues, storage, and AI services. 

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from aerostack.models.services_invoke200_response import ServicesInvoke200Response

class TestServicesInvoke200Response(unittest.TestCase):
    """ServicesInvoke200Response unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ServicesInvoke200Response:
        """Test ServicesInvoke200Response
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ServicesInvoke200Response`
        """
        model = ServicesInvoke200Response()
        if include_optional:
            return ServicesInvoke200Response(
                success = True,
                result = None
            )
        else:
            return ServicesInvoke200Response(
        )
        """

    def testServicesInvoke200Response(self):
        """Test ServicesInvoke200Response"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
