# coding: utf-8

"""
    Aerostack API

    Aerostack Platform API - Unified access to database, authentication,  caching, queues, storage, and AI services. 

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from aerostack.api.cache_api import CacheApi


class TestCacheApi(unittest.TestCase):
    """CacheApi unit test stubs"""

    def setUp(self) -> None:
        self.api = CacheApi()

    def tearDown(self) -> None:
        pass

    def test_cache_get(self) -> None:
        """Test case for cache_get

        Get cached value
        """
        pass

    def test_cache_set(self) -> None:
        """Test case for cache_set

        Set cached value
        """
        pass


if __name__ == '__main__':
    unittest.main()
