# coding: utf-8

"""
    Aerostack API

    Aerostack Platform API - Unified access to database, authentication,  caching, queues, storage, and AI services. 

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from aerostack.models.services_invoke_request import ServicesInvokeRequest

class TestServicesInvokeRequest(unittest.TestCase):
    """ServicesInvokeRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ServicesInvokeRequest:
        """Test ServicesInvokeRequest
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ServicesInvokeRequest`
        """
        model = ServicesInvokeRequest()
        if include_optional:
            return ServicesInvokeRequest(
                service_name = 'billing-webhook',
                data = {
                    'key' : null
                    }
            )
        else:
            return ServicesInvokeRequest(
                service_name = 'billing-webhook',
                data = {
                    'key' : null
                    },
        )
        """

    def testServicesInvokeRequest(self):
        """Test ServicesInvokeRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
