# coding: utf-8

"""
    Aerostack API

    Aerostack Platform API - Unified access to database, authentication,  caching, queues, storage, and AI services. 

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from aerostack.models.ai_chat_request import AiChatRequest

class TestAiChatRequest(unittest.TestCase):
    """AiChatRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> AiChatRequest:
        """Test AiChatRequest
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `AiChatRequest`
        """
        model = AiChatRequest()
        if include_optional:
            return AiChatRequest(
                model = '@cf/meta/llama-3-8b-instruct',
                messages = [
                    aerostack.models.ai_chat_request_messages_inner.aiChat_request_messages_inner(
                        role = 'system', 
                        content = '', )
                    ]
            )
        else:
            return AiChatRequest(
                messages = [
                    aerostack.models.ai_chat_request_messages_inner.aiChat_request_messages_inner(
                        role = 'system', 
                        content = '', )
                    ],
        )
        """

    def testAiChatRequest(self):
        """Test AiChatRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
