# coding: utf-8

"""
    Aerostack API

    Aerostack Platform API - Unified access to database, authentication,  caching, queues, storage, and AI services. 

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from aerostack.api.ai_api import AIApi


class TestAIApi(unittest.TestCase):
    """AIApi unit test stubs"""

    def setUp(self) -> None:
        self.api = AIApi()

    def tearDown(self) -> None:
        pass

    def test_ai_chat(self) -> None:
        """Test case for ai_chat

        Generate AI chat completion
        """
        pass

    def test_configure(self) -> None:
        """Test case for configure

        Update search configuration
        """
        pass

    def test_delete(self) -> None:
        """Test case for delete

        Delete item by ID
        """
        pass

    def test_delete_by_type(self) -> None:
        """Test case for delete_by_type

        Delete all items of a type
        """
        pass

    def test_ingest(self) -> None:
        """Test case for ingest

        Ingest content into managed search index
        """
        pass

    def test_list_types(self) -> None:
        """Test case for list_types

        List distinct types and counts
        """
        pass

    def test_query(self) -> None:
        """Test case for query

        Search managed index
        """
        pass


if __name__ == '__main__':
    unittest.main()
