# coding: utf-8

"""
    Aerostack API

    Aerostack Platform API - Unified access to database, authentication,  caching, queues, storage, and AI services. 

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from aerostack.models.query200_response import Query200Response

class TestQuery200Response(unittest.TestCase):
    """Query200Response unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> Query200Response:
        """Test Query200Response
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `Query200Response`
        """
        model = Query200Response()
        if include_optional:
            return Query200Response(
                results = [
                    aerostack.models.search_result.SearchResult(
                        id = '', 
                        content = '', 
                        score = 1.337, 
                        type = '', 
                        metadata = {
                            'key' : null
                            }, )
                    ]
            )
        else:
            return Query200Response(
        )
        """

    def testQuery200Response(self):
        """Test Query200Response"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
