# coding: utf-8

"""
    Aerostack API

    Aerostack Platform API - Unified access to database, authentication,  caching, queues, storage, and AI services. 

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from aerostack.models.ai_chat200_response import AiChat200Response

class TestAiChat200Response(unittest.TestCase):
    """AiChat200Response unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> AiChat200Response:
        """Test AiChat200Response
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `AiChat200Response`
        """
        model = AiChat200Response()
        if include_optional:
            return AiChat200Response(
                response = ''
            )
        else:
            return AiChat200Response(
        )
        """

    def testAiChat200Response(self):
        """Test AiChat200Response"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
