# coding: utf-8

"""
    Aerostack API

    Aerostack Platform API - Unified access to database, authentication,  caching, queues, storage, and AI services. 

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from aerostack.models.gateway_billing_log200_response import GatewayBillingLog200Response

class TestGatewayBillingLog200Response(unittest.TestCase):
    """GatewayBillingLog200Response unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> GatewayBillingLog200Response:
        """Test GatewayBillingLog200Response
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `GatewayBillingLog200Response`
        """
        model = GatewayBillingLog200Response()
        if include_optional:
            return GatewayBillingLog200Response(
                success = True,
                logged_units = 56
            )
        else:
            return GatewayBillingLog200Response(
        )
        """

    def testGatewayBillingLog200Response(self):
        """Test GatewayBillingLog200Response"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
