# coding: utf-8

"""
    Aerostack API

    Aerostack Platform API - Unified access to database, authentication,  caching, queues, storage, and AI services. 

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from aerostack.api.gateway_api import GatewayApi


class TestGatewayApi(unittest.TestCase):
    """GatewayApi unit test stubs"""

    def setUp(self) -> None:
        self.api = GatewayApi()

    def tearDown(self) -> None:
        pass

    def test_gateway_billing_log(self) -> None:
        """Test case for gateway_billing_log

        Log Gateway usage
        """
        pass


if __name__ == '__main__':
    unittest.main()
