# coding: utf-8

"""
    Aerostack API

    Aerostack Platform API - Unified access to database, authentication,  caching, queues, storage, and AI services. 

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from aerostack.models.storage_upload200_response import StorageUpload200Response

class TestStorageUpload200Response(unittest.TestCase):
    """StorageUpload200Response unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> StorageUpload200Response:
        """Test StorageUpload200Response
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `StorageUpload200Response`
        """
        model = StorageUpload200Response()
        if include_optional:
            return StorageUpload200Response(
                url = 'https://cdn.aerostack.ai/projects/abc/avatars/user-123.jpg'
            )
        else:
            return StorageUpload200Response(
        )
        """

    def testStorageUpload200Response(self):
        """Test StorageUpload200Response"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
