# coding: utf-8

"""
    Aerostack API

    Aerostack Platform API - Unified access to database, authentication,  caching, queues, storage, and AI services. 

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from aerostack.models.list_types200_response import ListTypes200Response

class TestListTypes200Response(unittest.TestCase):
    """ListTypes200Response unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ListTypes200Response:
        """Test ListTypes200Response
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ListTypes200Response`
        """
        model = ListTypes200Response()
        if include_optional:
            return ListTypes200Response(
                types = [
                    aerostack.models.type_stats.TypeStats(
                        type = '', 
                        count = 56, )
                    ]
            )
        else:
            return ListTypes200Response(
        )
        """

    def testListTypes200Response(self):
        """Test ListTypes200Response"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
