# coding: utf-8

"""
    Aerostack API

    Aerostack Platform API - Unified access to database, authentication,  caching, queues, storage, and AI services. 

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from aerostack.models.cache_get_request import CacheGetRequest

class TestCacheGetRequest(unittest.TestCase):
    """CacheGetRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> CacheGetRequest:
        """Test CacheGetRequest
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `CacheGetRequest`
        """
        model = CacheGetRequest()
        if include_optional:
            return CacheGetRequest(
                key = 'user:123:profile'
            )
        else:
            return CacheGetRequest(
                key = 'user:123:profile',
        )
        """

    def testCacheGetRequest(self):
        """Test CacheGetRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
