# coding: utf-8

"""
    Aerostack API

    Aerostack Platform API - Unified access to database, authentication,  caching, queues, storage, and AI services. 

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from aerostack.api.queue_api import QueueApi


class TestQueueApi(unittest.TestCase):
    """QueueApi unit test stubs"""

    def setUp(self) -> None:
        self.api = QueueApi()

    def tearDown(self) -> None:
        pass

    def test_queue_enqueue(self) -> None:
        """Test case for queue_enqueue

        Add job to queue
        """
        pass


if __name__ == '__main__':
    unittest.main()
