# coding: utf-8

"""
    Aerostack API

    Aerostack Platform API - Unified access to database, authentication,  caching, queues, storage, and AI services. 

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from aerostack.models.gateway_billing_log_request import GatewayBillingLogRequest

class TestGatewayBillingLogRequest(unittest.TestCase):
    """GatewayBillingLogRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> GatewayBillingLogRequest:
        """Test GatewayBillingLogRequest
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `GatewayBillingLogRequest`
        """
        model = GatewayBillingLogRequest()
        if include_optional:
            return GatewayBillingLogRequest(
                consumer_id = 'usr_123xyz',
                api_id = 'api_chat_bot',
                metric = 'tokens',
                units = 1500
            )
        else:
            return GatewayBillingLogRequest(
                consumer_id = 'usr_123xyz',
                api_id = 'api_chat_bot',
                units = 1500,
        )
        """

    def testGatewayBillingLogRequest(self):
        """Test GatewayBillingLogRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
