# coding: utf-8

"""
    Aerostack API

    Aerostack Platform API - Unified access to database, authentication,  caching, queues, storage, and AI services. 

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from aerostack.api.authentication_api import AuthenticationApi


class TestAuthenticationApi(unittest.TestCase):
    """AuthenticationApi unit test stubs"""

    def setUp(self) -> None:
        self.api = AuthenticationApi()

    def tearDown(self) -> None:
        pass

    def test_auth_signin(self) -> None:
        """Test case for auth_signin

        Sign in user
        """
        pass

    def test_auth_signup(self) -> None:
        """Test case for auth_signup

        Sign up new user
        """
        pass


if __name__ == '__main__':
    unittest.main()
