# coding: utf-8

"""
    Aerostack API

    Aerostack Platform API - Unified access to database, authentication, caching, queues, storage, and AI services. 

    The version of the OpenAPI document: 1.5.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json


from typing import Any, ClassVar, Dict, List, Optional, Union
from pydantic import BaseModel, StrictBool, StrictStr
from pydantic import Field
from typing_extensions import Annotated
from aerostack.models.chat_completion_request_stream_options import ChatCompletionRequestStreamOptions
from aerostack.models.chat_message import ChatMessage
try:
    from typing import Self
except ImportError:
    from typing_extensions import Self

class ChatCompletionRequest(BaseModel):
    """
    ChatCompletionRequest
    """ # noqa: E501
    model: Optional[StrictStr] = Field(default=None, description="Model identifier (provider-specific)")
    messages: List[ChatMessage]
    stream: Optional[StrictBool] = Field(default=False, description="When true, returns a server-sent events (SSE) stream of token deltas. Each event is `data: <json>\\n\\n`. The stream ends with `data: [DONE]\\n\\n`. ")
    stream_options: Optional[ChatCompletionRequestStreamOptions] = None
    temperature: Optional[Union[Annotated[float, Field(le=2, strict=True, ge=0)], Annotated[int, Field(le=2, strict=True, ge=0)]]] = Field(default=None, description="Sampling temperature (0=deterministic, 2=creative)")
    max_tokens: Optional[Annotated[int, Field(strict=True, ge=1)]] = Field(default=None, description="Maximum tokens to generate")
    top_p: Optional[Union[Annotated[float, Field(le=1, strict=True, ge=0)], Annotated[int, Field(le=1, strict=True, ge=0)]]] = Field(default=None, description="Nucleus sampling probability")
    __properties: ClassVar[List[str]] = ["model", "messages", "stream", "stream_options", "temperature", "max_tokens", "top_p"]

    model_config = {
        "populate_by_name": True,
        "validate_assignment": True,
        "protected_namespaces": (),
    }


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of ChatCompletionRequest from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        _dict = self.model_dump(
            by_alias=True,
            exclude={
            },
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each item in messages (list)
        _items = []
        if self.messages:
            for _item in self.messages:
                if _item:
                    _items.append(_item.to_dict())
            _dict['messages'] = _items
        # override the default output from pydantic by calling `to_dict()` of stream_options
        if self.stream_options:
            _dict['stream_options'] = self.stream_options.to_dict()
        return _dict

    @classmethod
    def from_dict(cls, obj: Dict) -> Self:
        """Create an instance of ChatCompletionRequest from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "model": obj.get("model"),
            "messages": [ChatMessage.from_dict(_item) for _item in obj.get("messages")] if obj.get("messages") is not None else None,
            "stream": obj.get("stream") if obj.get("stream") is not None else False,
            "stream_options": ChatCompletionRequestStreamOptions.from_dict(obj.get("stream_options")) if obj.get("stream_options") is not None else None,
            "temperature": obj.get("temperature"),
            "max_tokens": obj.get("max_tokens"),
            "top_p": obj.get("top_p")
        })
        return _obj


