"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from typing import TYPE_CHECKING
from importlib import import_module
import builtins
import sys

if TYPE_CHECKING:
    from .aichatop import (
        AiChatRequestBody,
        AiChatRequestBodyTypedDict,
        AiChatResponseBody,
        AiChatResponseBodyTypedDict,
        Messages,
        MessagesTypedDict,
        Role,
    )
    from .authresponse import AuthResponse, AuthResponseTypedDict
    from .authsigninop import AuthSigninRequestBody, AuthSigninRequestBodyTypedDict
    from .authsignupop import AuthSignupRequestBody, AuthSignupRequestBodyTypedDict
    from .cachegetop import (
        CacheGetRequestBody,
        CacheGetRequestBodyTypedDict,
        CacheGetResponseBody,
        CacheGetResponseBodyTypedDict,
    )
    from .cachesetop import (
        CacheSetRequestBody,
        CacheSetRequestBodyTypedDict,
        CacheSetResponseBody,
        CacheSetResponseBodyTypedDict,
    )
    from .configureop import (
        ConfigureRequestBody,
        ConfigureRequestBodyTypedDict,
        ConfigureResponseBody,
        ConfigureResponseBodyTypedDict,
        EmbeddingModel,
    )
    from .dbqueryop import DbQueryRequestBody, DbQueryRequestBodyTypedDict
    from .dbqueryresult import DbQueryResult, DbQueryResultTypedDict
    from .deletebytypeop import (
        DeleteByTypeRequestBody,
        DeleteByTypeRequestBodyTypedDict,
        DeleteByTypeResponseBody,
        DeleteByTypeResponseBodyTypedDict,
    )
    from .deleteop import (
        DeleteRequestBody,
        DeleteRequestBodyTypedDict,
        DeleteResponseBody,
        DeleteResponseBodyTypedDict,
    )
    from .ingestop import (
        IngestRequestBody,
        IngestRequestBodyTypedDict,
        IngestResponseBody,
        IngestResponseBodyTypedDict,
    )
    from .listtypesop import ListTypesResponseBody, ListTypesResponseBodyTypedDict
    from .queryop import (
        QueryRequestBody,
        QueryRequestBodyTypedDict,
        QueryResponseBody,
        QueryResponseBodyTypedDict,
    )
    from .queueenqueueop import (
        QueueEnqueueRequestBody,
        QueueEnqueueRequestBodyTypedDict,
        QueueEnqueueResponseBody,
        QueueEnqueueResponseBodyTypedDict,
    )
    from .searchresult import SearchResult, SearchResultTypedDict
    from .security import Security, SecurityTypedDict
    from .servicesinvokeop import (
        ServicesInvokeRequestBody,
        ServicesInvokeRequestBodyTypedDict,
        ServicesInvokeResponseBody,
        ServicesInvokeResponseBodyTypedDict,
    )
    from .storageuploadop import (
        File,
        FileTypedDict,
        StorageUploadRequestBody,
        StorageUploadRequestBodyTypedDict,
        StorageUploadResponseBody,
        StorageUploadResponseBodyTypedDict,
    )
    from .typestats import TypeStats, TypeStatsTypedDict
    from .user import User, UserTypedDict

__all__ = [
    "AiChatRequestBody",
    "AiChatRequestBodyTypedDict",
    "AiChatResponseBody",
    "AiChatResponseBodyTypedDict",
    "AuthResponse",
    "AuthResponseTypedDict",
    "AuthSigninRequestBody",
    "AuthSigninRequestBodyTypedDict",
    "AuthSignupRequestBody",
    "AuthSignupRequestBodyTypedDict",
    "CacheGetRequestBody",
    "CacheGetRequestBodyTypedDict",
    "CacheGetResponseBody",
    "CacheGetResponseBodyTypedDict",
    "CacheSetRequestBody",
    "CacheSetRequestBodyTypedDict",
    "CacheSetResponseBody",
    "CacheSetResponseBodyTypedDict",
    "ConfigureRequestBody",
    "ConfigureRequestBodyTypedDict",
    "ConfigureResponseBody",
    "ConfigureResponseBodyTypedDict",
    "DbQueryRequestBody",
    "DbQueryRequestBodyTypedDict",
    "DbQueryResult",
    "DbQueryResultTypedDict",
    "DeleteByTypeRequestBody",
    "DeleteByTypeRequestBodyTypedDict",
    "DeleteByTypeResponseBody",
    "DeleteByTypeResponseBodyTypedDict",
    "DeleteRequestBody",
    "DeleteRequestBodyTypedDict",
    "DeleteResponseBody",
    "DeleteResponseBodyTypedDict",
    "EmbeddingModel",
    "File",
    "FileTypedDict",
    "IngestRequestBody",
    "IngestRequestBodyTypedDict",
    "IngestResponseBody",
    "IngestResponseBodyTypedDict",
    "ListTypesResponseBody",
    "ListTypesResponseBodyTypedDict",
    "Messages",
    "MessagesTypedDict",
    "QueryRequestBody",
    "QueryRequestBodyTypedDict",
    "QueryResponseBody",
    "QueryResponseBodyTypedDict",
    "QueueEnqueueRequestBody",
    "QueueEnqueueRequestBodyTypedDict",
    "QueueEnqueueResponseBody",
    "QueueEnqueueResponseBodyTypedDict",
    "Role",
    "SearchResult",
    "SearchResultTypedDict",
    "Security",
    "SecurityTypedDict",
    "ServicesInvokeRequestBody",
    "ServicesInvokeRequestBodyTypedDict",
    "ServicesInvokeResponseBody",
    "ServicesInvokeResponseBodyTypedDict",
    "StorageUploadRequestBody",
    "StorageUploadRequestBodyTypedDict",
    "StorageUploadResponseBody",
    "StorageUploadResponseBodyTypedDict",
    "TypeStats",
    "TypeStatsTypedDict",
    "User",
    "UserTypedDict",
]

_dynamic_imports: dict[str, str] = {
    "AiChatRequestBody": ".aichatop",
    "AiChatRequestBodyTypedDict": ".aichatop",
    "AiChatResponseBody": ".aichatop",
    "AiChatResponseBodyTypedDict": ".aichatop",
    "Messages": ".aichatop",
    "MessagesTypedDict": ".aichatop",
    "Role": ".aichatop",
    "AuthResponse": ".authresponse",
    "AuthResponseTypedDict": ".authresponse",
    "AuthSigninRequestBody": ".authsigninop",
    "AuthSigninRequestBodyTypedDict": ".authsigninop",
    "AuthSignupRequestBody": ".authsignupop",
    "AuthSignupRequestBodyTypedDict": ".authsignupop",
    "CacheGetRequestBody": ".cachegetop",
    "CacheGetRequestBodyTypedDict": ".cachegetop",
    "CacheGetResponseBody": ".cachegetop",
    "CacheGetResponseBodyTypedDict": ".cachegetop",
    "CacheSetRequestBody": ".cachesetop",
    "CacheSetRequestBodyTypedDict": ".cachesetop",
    "CacheSetResponseBody": ".cachesetop",
    "CacheSetResponseBodyTypedDict": ".cachesetop",
    "ConfigureRequestBody": ".configureop",
    "ConfigureRequestBodyTypedDict": ".configureop",
    "ConfigureResponseBody": ".configureop",
    "ConfigureResponseBodyTypedDict": ".configureop",
    "EmbeddingModel": ".configureop",
    "DbQueryRequestBody": ".dbqueryop",
    "DbQueryRequestBodyTypedDict": ".dbqueryop",
    "DbQueryResult": ".dbqueryresult",
    "DbQueryResultTypedDict": ".dbqueryresult",
    "DeleteByTypeRequestBody": ".deletebytypeop",
    "DeleteByTypeRequestBodyTypedDict": ".deletebytypeop",
    "DeleteByTypeResponseBody": ".deletebytypeop",
    "DeleteByTypeResponseBodyTypedDict": ".deletebytypeop",
    "DeleteRequestBody": ".deleteop",
    "DeleteRequestBodyTypedDict": ".deleteop",
    "DeleteResponseBody": ".deleteop",
    "DeleteResponseBodyTypedDict": ".deleteop",
    "IngestRequestBody": ".ingestop",
    "IngestRequestBodyTypedDict": ".ingestop",
    "IngestResponseBody": ".ingestop",
    "IngestResponseBodyTypedDict": ".ingestop",
    "ListTypesResponseBody": ".listtypesop",
    "ListTypesResponseBodyTypedDict": ".listtypesop",
    "QueryRequestBody": ".queryop",
    "QueryRequestBodyTypedDict": ".queryop",
    "QueryResponseBody": ".queryop",
    "QueryResponseBodyTypedDict": ".queryop",
    "QueueEnqueueRequestBody": ".queueenqueueop",
    "QueueEnqueueRequestBodyTypedDict": ".queueenqueueop",
    "QueueEnqueueResponseBody": ".queueenqueueop",
    "QueueEnqueueResponseBodyTypedDict": ".queueenqueueop",
    "SearchResult": ".searchresult",
    "SearchResultTypedDict": ".searchresult",
    "Security": ".security",
    "SecurityTypedDict": ".security",
    "ServicesInvokeRequestBody": ".servicesinvokeop",
    "ServicesInvokeRequestBodyTypedDict": ".servicesinvokeop",
    "ServicesInvokeResponseBody": ".servicesinvokeop",
    "ServicesInvokeResponseBodyTypedDict": ".servicesinvokeop",
    "File": ".storageuploadop",
    "FileTypedDict": ".storageuploadop",
    "StorageUploadRequestBody": ".storageuploadop",
    "StorageUploadRequestBodyTypedDict": ".storageuploadop",
    "StorageUploadResponseBody": ".storageuploadop",
    "StorageUploadResponseBodyTypedDict": ".storageuploadop",
    "TypeStats": ".typestats",
    "TypeStatsTypedDict": ".typestats",
    "User": ".user",
    "UserTypedDict": ".user",
}


def dynamic_import(modname, retries=3):
    for attempt in range(retries):
        try:
            return import_module(modname, __package__)
        except KeyError:
            # Clear any half-initialized module and retry
            sys.modules.pop(modname, None)
            if attempt == retries - 1:
                break
    raise KeyError(f"Failed to import module '{modname}' after {retries} attempts")


def __getattr__(attr_name: str) -> object:
    module_name = _dynamic_imports.get(attr_name)
    if module_name is None:
        raise AttributeError(
            f"No {attr_name} found in _dynamic_imports for module name -> {__name__} "
        )

    try:
        module = dynamic_import(module_name)
        result = getattr(module, attr_name)
        return result
    except ImportError as e:
        raise ImportError(
            f"Failed to import {attr_name} from {module_name}: {e}"
        ) from e
    except AttributeError as e:
        raise AttributeError(
            f"Failed to get {attr_name} from {module_name}: {e}"
        ) from e


def __dir__():
    lazy_attrs = builtins.list(_dynamic_imports.keys())
    return builtins.sorted(lazy_attrs)
