"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from aerostack.types import BaseModel, UNSET_SENTINEL
import pydantic
from pydantic import model_serializer
from typing import Optional
from typing_extensions import Annotated, NotRequired, TypedDict


class GatewayBillingLogRequestBodyTypedDict(TypedDict):
    consumer_id: str
    r"""The Consumer ID making the request"""
    api_id: str
    r"""The Developer Gateway API ID being consumed"""
    units: int
    r"""Amount of usage to log"""
    metric: NotRequired[str]
    r"""Optional metric name (default: 'units')"""


class GatewayBillingLogRequestBody(BaseModel):
    consumer_id: Annotated[str, pydantic.Field(alias="consumerId")]
    r"""The Consumer ID making the request"""

    api_id: Annotated[str, pydantic.Field(alias="apiId")]
    r"""The Developer Gateway API ID being consumed"""

    units: int
    r"""Amount of usage to log"""

    metric: Optional[str] = None
    r"""Optional metric name (default: 'units')"""

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["metric"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k)

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m


class GatewayBillingLogResponseBodyTypedDict(TypedDict):
    r"""Usage logged successfully"""

    success: NotRequired[bool]
    logged_units: NotRequired[int]


class GatewayBillingLogResponseBody(BaseModel):
    r"""Usage logged successfully"""

    success: Optional[bool] = None

    logged_units: Annotated[Optional[int], pydantic.Field(alias="loggedUnits")] = None

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["success", "loggedUnits"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k)

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m


try:
    GatewayBillingLogRequestBody.model_rebuild()
except NameError:
    pass
try:
    GatewayBillingLogResponseBody.model_rebuild()
except NameError:
    pass
