"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .searchresult import SearchResult, SearchResultTypedDict
from aerostack.types import BaseModel, UNSET_SENTINEL
import pydantic
from pydantic import model_serializer
from typing import Any, Dict, List, Optional
from typing_extensions import Annotated, NotRequired, TypedDict


class QueryRequestBodyTypedDict(TypedDict):
    text: str
    top_k: NotRequired[int]
    types: NotRequired[List[str]]
    filter_: NotRequired[Dict[str, Any]]


class QueryRequestBody(BaseModel):
    text: str

    top_k: Annotated[Optional[int], pydantic.Field(alias="topK")] = 5

    types: Optional[List[str]] = None

    filter_: Annotated[Optional[Dict[str, Any]], pydantic.Field(alias="filter")] = None

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["topK", "types", "filter"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k)

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m


class QueryResponseBodyTypedDict(TypedDict):
    r"""Search results"""

    results: NotRequired[List[SearchResultTypedDict]]


class QueryResponseBody(BaseModel):
    r"""Search results"""

    results: Optional[List[SearchResult]] = None

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["results"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k)

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m


try:
    QueryRequestBody.model_rebuild()
except NameError:
    pass
