"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from aerostack.types import BaseModel, UNSET_SENTINEL
from pydantic import model_serializer
from typing import Any, Dict, Optional
from typing_extensions import NotRequired, TypedDict


class SearchResultTypedDict(TypedDict):
    id: NotRequired[str]
    content: NotRequired[str]
    score: NotRequired[float]
    type: NotRequired[str]
    metadata: NotRequired[Dict[str, Any]]


class SearchResult(BaseModel):
    id: Optional[str] = None

    content: Optional[str] = None

    score: Optional[float] = None

    type: Optional[str] = None

    metadata: Optional[Dict[str, Any]] = None

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["id", "content", "score", "type", "metadata"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k)

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m
