"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from aerostack.types import BaseModel, UNSET_SENTINEL
import pydantic
from pydantic import model_serializer
from typing import Any, Dict, Optional
from typing_extensions import Annotated, NotRequired, TypedDict


class ServicesInvokeRequestBodyTypedDict(TypedDict):
    service_name: str
    data: Dict[str, Any]


class ServicesInvokeRequestBody(BaseModel):
    service_name: Annotated[str, pydantic.Field(alias="serviceName")]

    data: Dict[str, Any]


class ServicesInvokeResponseBodyTypedDict(TypedDict):
    r"""Service invoked successfully"""

    success: NotRequired[bool]
    result: NotRequired[Any]


class ServicesInvokeResponseBody(BaseModel):
    r"""Service invoked successfully"""

    success: Optional[bool] = None

    result: Optional[Any] = None

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["success", "result"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k)

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m


try:
    ServicesInvokeRequestBody.model_rebuild()
except NameError:
    pass
