"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from aerostack.types import BaseModel, Nullable, OptionalNullable, UNSET, UNSET_SENTINEL
from datetime import datetime
import pydantic
from pydantic import model_serializer
from typing import Any, Dict, Optional
from typing_extensions import Annotated, NotRequired, TypedDict


class UserTypedDict(TypedDict):
    id: NotRequired[str]
    email: NotRequired[str]
    name: NotRequired[Nullable[str]]
    created_at: NotRequired[datetime]
    metadata: NotRequired[Dict[str, Any]]


class User(BaseModel):
    id: Optional[str] = None

    email: Optional[str] = None

    name: OptionalNullable[str] = UNSET

    created_at: Annotated[Optional[datetime], pydantic.Field(alias="createdAt")] = None

    metadata: Optional[Dict[str, Any]] = None

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["id", "email", "name", "createdAt", "metadata"])
        nullable_fields = set(["name"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k)
            is_nullable_and_explicitly_set = (
                k in nullable_fields
                and (self.__pydantic_fields_set__.intersection({n}))  # pylint: disable=no-member
            )

            if val != UNSET_SENTINEL:
                if (
                    val is not None
                    or k not in optional_fields
                    or is_nullable_and_explicitly_set
                ):
                    m[k] = val

        return m


try:
    User.model_rebuild()
except NameError:
    pass
