# coding: utf-8

# flake8: noqa

"""
    Aerostack API

    Aerostack Platform API - Unified access to database, authentication,  caching, queues, storage, and AI services. 

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


__version__ = "1.0.0"

from aerostack.sdk import SDK

# import apis into sdk package
from aerostack.api.ai_api import AIApi
from aerostack.api.authentication_api import AuthenticationApi
from aerostack.api.cache_api import CacheApi
from aerostack.api.database_api import DatabaseApi
from aerostack.api.gateway_api import GatewayApi
from aerostack.api.queue_api import QueueApi
from aerostack.api.services_api import ServicesApi
from aerostack.api.storage_api import StorageApi

# import ApiClient
from aerostack.api_response import ApiResponse
from aerostack.api_client import ApiClient
from aerostack.configuration import Configuration
from aerostack.exceptions import OpenApiException
from aerostack.exceptions import ApiTypeError
from aerostack.exceptions import ApiValueError
from aerostack.exceptions import ApiKeyError
from aerostack.exceptions import ApiAttributeError
from aerostack.exceptions import ApiException

# import models into sdk package
from aerostack.models.ai_chat200_response import AiChat200Response
from aerostack.models.ai_chat_request import AiChatRequest
from aerostack.models.ai_chat_request_messages_inner import AiChatRequestMessagesInner
from aerostack.models.auth_response import AuthResponse
from aerostack.models.auth_signin_request import AuthSigninRequest
from aerostack.models.auth_signup_request import AuthSignupRequest
from aerostack.models.cache_get200_response import CacheGet200Response
from aerostack.models.cache_get_request import CacheGetRequest
from aerostack.models.cache_set200_response import CacheSet200Response
from aerostack.models.cache_set_request import CacheSetRequest
from aerostack.models.configure_request import ConfigureRequest
from aerostack.models.db_query_request import DbQueryRequest
from aerostack.models.db_query_result import DbQueryResult
from aerostack.models.delete_by_type_request import DeleteByTypeRequest
from aerostack.models.delete_request import DeleteRequest
from aerostack.models.error_response import ErrorResponse
from aerostack.models.gateway_billing_log200_response import GatewayBillingLog200Response
from aerostack.models.gateway_billing_log_request import GatewayBillingLogRequest
from aerostack.models.ingest_request import IngestRequest
from aerostack.models.list_types200_response import ListTypes200Response
from aerostack.models.query200_response import Query200Response
from aerostack.models.query_request import QueryRequest
from aerostack.models.queue_enqueue201_response import QueueEnqueue201Response
from aerostack.models.queue_enqueue_request import QueueEnqueueRequest
from aerostack.models.search_result import SearchResult
from aerostack.models.services_invoke200_response import ServicesInvoke200Response
from aerostack.models.services_invoke_request import ServicesInvokeRequest
from aerostack.models.storage_upload200_response import StorageUpload200Response
from aerostack.models.type_stats import TypeStats
from aerostack.models.user import User
